### ISSUE TITLE
bunch of errors during compile

### ISSUE THREAD

**Issue by tehseensagar** [tenable/routeros#10]
version-Ubuntu-18:
----------------------------

Getting bunch of errors after running 

make

[ 20%] Building CXX object CMakeFiles/message_tests.dir/src/winbox_parse_json_test.cpp.o
/opt/routeros-master/tests/src/winbox_parse_json_test.cpp:1:10: fatal error: gtest/gtest.h: No such file or directory
 #include <gtest/gtest.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/message_tests.dir/build.make:62: recipe for target 'CMakeFiles/message_tests.dir/src/winbox_parse_json_test.cpp.o' failed
make[2]: *** [CMakeFiles/message_tests.dir/src/winbox_parse_json_test.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/message_tests.dir/all' failed
make[1]: *** [CMakeFiles/message_tests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I don't thing so I left with any dependencies.

Regards

**Comment by tehseensagar** [comment]
issue is fixed , one of the deps  was missing.

Solution:
----------------
apt-get install libgtest-dev


After runing make again now getting following errors 

usr/bin/ld: cannot find -lgtest
/usr/bin/ld: cannot find -lgtest_main
collect2: error: ld returned 1 exit status
CMakeFiles/message_tests.dir/build.make:172: recipe for target 'message_tests' failed
make[2]: *** [message_tests] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/message_tests.dir/all' failed
make[1]: *** [CMakeFiles/message_tests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jacob-baines** [comment]
What are trying to compile? Just the tests?

What version of Ubuntu 18? .04? .10?

**Comment by tehseensagar** [comment]
ubuntu 18.04

**Comment by jacob-baines** [comment]
Gotcha.

Apparently, when you apt get libgtest-dev it only installs the source files. You have to actually build library still (I have no idea why this would be but whatever). I just followed the instructions from here:

https://stackoverflow.com/questions/24295876/cmake-cannot-find-googletest-required-library-in-ubuntu

Basically:
```sh
sudo apt install libgtest-dev
cd /usr/src/googletest/
sudo cmake .
sudo cmake --build . --target install
```

I hope that clears things up for you.
