### ISSUE TITLE
winbox pcap cannot parse

### ISSUE THREAD

**Issue by hanjideng** [tenable/routeros#14]
I use winbox v3.18 to communicate with routeros 6.41.3, i captured before i click connect, and then i saved all data to pcap file format.
The problem is when i use winbox_pcap_parse to parse the pcap file, it print as follow:
Opening upload.pcap
Server side parsing error.
Server side parsing error.
Server side parsing error.
Server side parsing error.
Server side parsing error.
...
DONE
It seems that parse error, please help me

**Comment by jacob-baines** [comment]
Hello @hanjideng. The parser only works on unencrypted connections. Furthermore, in order to debug this I'd need the pcap to reproduce the issue.

**Comment by hanjideng** [comment]
Now I find the reason, the winbox i use is the newest version, so it use safe mode as default, and i cannot turn it off.
![image](https://user-images.githubusercontent.com/7285031/57510129-906df980-7338-11e9-969b-0e410e56fcf5.png)
